name = "Turret Lock";
author = "johnb43";
tooltip = "Turret Lock";
tooltipOwned = "Turret Lock";
hideName = 0;
hidePicture = 0;
actionName = "Github";
action = "https://github.com/johnb432/Turret-Lock";
description = "Adds the ability to lock and unlock stabilized turrets. Made by johnb43";
overview = "Adds the ability to lock and unlock stabilized turrets. Made by johnb43";
picture = "\x\turret_lock\addons\main\ui\logo_turret_lock.paa"; // http://getdrawings.com/get-drawing#army-tank-drawing-61.jpg
logo = "\x\turret_lock\addons\main\ui\logo_turret_lock.paa";
logoOver = "\x\turret_lock\addons\main\ui\logo_turret_lock.paa";
logoSmall = "\x\turret_lock\addons\main\ui\logo_turret_lock.paa";
overviewPicture = "\x\turret_lock\addons\main\ui\logo_turret_lock.paa";
