name = "Turret-Lock"
prefix = "turret_lock"
author = "johnb43"
template = "cba"
mainprefix = "x"
files = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
folder_optionals = false
sig_version = 3
